name: radio_braulio
description: Listen to radio stations from all over the world.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  just_audio: ^0.9.39
  cached_network_image: ^3.3.1
  volume_controller: ^2.0.7
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true